
spring.application.name=ms-alertas-consumer-json

# Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@bdy2201db_low
spring.datasource.username=ESQUEMA_ALERTAS
spring.datasource.password=Bdy2201@2026

# Wallet
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=C:/fullstack_dev/proyecto-alertas-medicas/backend/microservices/ms-alertas/Wallet_BDY2201DB

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Hikari
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# Actuator
management.endpoints.web.exposure.include=health,info

# Port
server.port=8084