spring.application.name=ms-alertas

# =========================
# DATABASE (LOCAL / DOCKER)
# =========================
spring.datasource.url=jdbc:oracle:thin:@//host.docker.internal:1521/XEPDB1
spring.datasource.username=local_user
spring.datasource.password=local_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# =========================
# HIKARI (POOL)
# =========================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info